name: Cargo publish

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: publish on crates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: cargo login --config KEY=${{ secrets.CRATES_TOKEN }}
      - run: cargo publish
      


      
  
